### ISSUE TITLE
Trouble with the actual Download

### ISSUE THREAD

**Issue by John-Ark** [John-Ark/MP3Converter#1]
Greetings!

While this is written on the README file, I will repeat it here.

There is an issue downloading CERTAIN videos, I get an error related to encoding, I'd love any help I could get.

Figured this was also a good opportunity to try to open an issue here on Github, so this is my first time trying this.

Thank you for the help in advance!

**Comment by AlexHoop140** [comment]
> Greetings!
> 
> While this is written on the README file, I will repeat it here.
> 
> There is an issue downloading CERTAIN videos, I get an error related to encoding, I'd love any help I could get.
> 
> Figured this was also a good opportunity to try to open an issue here on Github, so this is my first time trying this.
> 
> Thank you for the help in advance!

Hi, I saw your issue. I ran the program on some links, some files can play on Windows Media Player, others cannot. Is that your problem? I tried to play on VLC instead of WMP, it worked!

**Comment by John-Ark** [comment]
> > Greetings!
> > While this is written on the README file, I will repeat it here.
> > There is an issue downloading CERTAIN videos, I get an error related to encoding, I'd love any help I could get.
> > Figured this was also a good opportunity to try to open an issue here on Github, so this is my first time trying this.
> > Thank you for the help in advance!
> 
> Hi, I saw your issue. I ran the program on some links, some files can play on Windows Media Player, others cannot. Is that your problem? I tried to play on VLC instead of WMP, it worked!

Hi! Thank you for giving it a look, yes that's precisely what I meant. I was running this on the Windows Media Player also, and some worked while others didn't. What's VLC stand for by the way? Only ever used WMP.

**Comment by John-Ark** [comment]
Hi! Thank you for giving it a look, yes that's precisely what I meant. I was running this on the Windows Media Player also, and some worked while others didn't. What's VLC stand for by the way? Only ever used WMP. (Ignore the closing, I am still getting used to using this haha)

**Comment by AlexHoop140** [comment]
> Hi! Thank you for giving it a look, yes that's precisely what I meant. I was running this on the Windows Media Player also, and some worked while others didn't. What's VLC stand for by the way? Only ever used WMP. (Ignore the closing, I am still getting used to using this haha)

It's just an open-source media player. You can download it [here](https://www.videolan.org/vlc/).
I think the problem lies with Windows Media Player; it may not support the proper codecs for the MP3 file.
Like this problem: [Link 1](https://answers.microsoft.com/en-us/windows/forum/all/why-cant-windows-10-media-player-open-some-mp4/31dfc15d-74fd-4cf1-ae37-21f038ea94f4)
I also used the tool recommended in the link above, but there was almost no difference between the files...

Or this: [Link 2](https://www.quora.com/The-video-I-downloaded-online-cannot-play-in-VLC-Windows-Media-Player-have-sound-but-no-image-but-the-video-can-be-played-in-MPC-HC-GOM-image-stuck-but-at-least-playable-Does-the-mp4-file-got-virus-What-is-happening)

It's also my first time replying to an issue. :v

**Comment by John-Ark** [comment]
> > Hi! Thank you for giving it a look, yes that's precisely what I meant. I was running this on the Windows Media Player also, and some worked while others didn't. What's VLC stand for by the way? Only ever used WMP. (Ignore the closing, I am still getting used to using this haha)
> 
> It's just an open-source media player. You can download it [here](https://www.videolan.org/vlc/). I think the problem lies with Windows Media Player; it may not support the proper codecs for the MP3 file. Like this problem: [Link 1](https://answers.microsoft.com/en-us/windows/forum/all/why-cant-windows-10-media-player-open-some-mp4/31dfc15d-74fd-4cf1-ae37-21f038ea94f4) I also used the tool recommended in the link above, but there was almost no difference between the files...
> 
> Or this: [Link 2](https://www.quora.com/The-video-I-downloaded-online-cannot-play-in-VLC-Windows-Media-Player-have-sound-but-no-image-but-the-video-can-be-played-in-MPC-HC-GOM-image-stuck-but-at-least-playable-Does-the-mp4-file-got-virus-What-is-happening)
> 
> It's also my first time replying to an issue. :v

Awesome to hear it's also the first time you're replying!

I am not so sure about the fault lying with WMP, there has to be something online converters do that makes everything work that I have failed to replicate... Not sure what to make of it. Maybe a limitation of the library I used perhaps?

Also thank you for the links! I forgot what VLC was but now I remember, just never actually checked what it was called.

I appreciate the input heavily though, I just figured I messed up my code (As one usually does), but it's nice to get a second opinion here as well. Thank you very much!

**Comment by AlexHoop140** [comment]
> Not sure what to make of it. Maybe a limitation of the library I used perhaps?

Yeh, maybe there are some limitations in the library.

> I appreciate the input heavily though, I just figured I messed up my code (As one usually does), but it's nice to get a second opinion here as well. Thank you very much!

I also messed up my code too. Not a problem at all!

**Comment by John-Ark** [comment]
I suppose I'll close the issue for now, I'll retry this again with a different library later on. 

Thank you again for you input! I appreciate it a lot. Have fun coding brother!
